apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.geonode.secret.existingSecretName }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: {{ .Values.vault.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.geonode.secret.existingSecretName }}
    creationPolicy: Owner
  data:
    {{- range $key, $val := .Values.geonode.secret.data }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ (index (splitList "#" $val) 0) }}
        property: {{ (index (splitList "#" $val) 1) }}
    {{- end }}