{{ if and (eq .Values.postgres.type "external") (not .Values.postgres.external.secret.existingSecretName )}}

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-geodata-external-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: {{ .Values.vault.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-geodata-external-secrets
    creationPolicy: Owner
  data:
    {{- range $key, $val := .Values.postgres.geodata.secret }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ (index (splitList "#" $val) 0) }}
        property: {{ (index (splitList "#" $val) 1) }}
    {{- end }}

{{- end }}
