{{- if .Values.postgres.cnpg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.postgres.cnpg.clusterName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: geonode-k8s
spec:
  # Image with PostGIS
  imageName: {{ .Values.postgres.cnpg.imageName }}

  # Number of instances (replicas)
  instances: {{ .Values.postgres.cnpg.instances }}

  # Primary update strategy
  primaryUpdateStrategy: unsupervised
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      work_mem: "16MB"
      maintenance_work_mem: "64MB"
  # Storage configuration
  storage:
    size: {{ .Values.postgres.cnpg.storage.size }}
    storageClass: {{ .Values.postgres.cnpg.storage.storageClass | default .Values.global.storageClass }}

  # Resources
  resources:
    requests:
      cpu: {{ .Values.postgres.cnpg.resources.requests.cpu }}
      memory: {{ .Values.postgres.cnpg.resources.requests.memory }}
    limits:
      cpu: {{ .Values.postgres.cnpg.resources.limits.cpu }}
      memory: {{ .Values.postgres.cnpg.resources.limits.memory }}

  # Affinity and tolerations
  affinity:
    # topologySpreadConstraints:
    #   - maxSkew: 1
    #     topologyKey: kubernetes.io/hostname
    #     whenUnsatisfiable: DeferSchedulingAheadOfScheduling
    #     labelSelector:
    #       matchLabels:
    #         postgresql: {{ .Values.postgres.cnpg.clusterName }}
    tolerations: {{ toYaml .Values.global.tolerations | nindent 6 }}

  # Bootstrap database initialization
  bootstrap:
    initdb:
      database: {{ .Values.postgres.bootstrap.initdb.database }}
      owner: {{ .Values.postgres.bootstrap.initdb.owner }}
      # Create secret with app user password (auto-generated by CNPG)
      secret:
        name: {{ .Values.postgres.cnpg.clusterName }}-app-secret
      # SQL scripts to initialize database
      {{- if .Values.postgres.bootstrap.initdb.scripts }}
      sql:
      {{- range .Values.postgres.bootstrap.initdb.scripts }}
        - |
          {{- .content | nindent 12 }}
      {{- end }}
      {{- end }}

  monitoring:	
    customQueriesConfigMap:	
      - key: queries	
        name: cnpg-default-monitoring	
    disableDefaultQueries: false	
    enablePodMonitor: false


{{- end }}