apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-cluster-pg-app
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.vault.secretStoreName }}
    kind: SecretStore
  target:
    name: cluster-pg-app
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: rheticus_electric_tower/data/postgres
        property: password
    - secretKey: postgres-password
      remoteRef:
        key: rheticus_electric_tower/data/postgres
        property: password
    - secretKey: geonode-password
      remoteRef:
        key: rheticus_electric_tower/data/geonode
        property: password
    - secretKey: geodata-password
      remoteRef:
        key: rheticus_electric_tower/data/geodata
        property: password

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-cnpg-geonode-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.vault.secretStoreName }}
    kind: SecretStore
  target:
    name: cnpg-geonode-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: rheticus_electric_tower/data/geonode
        property: password

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-cnpg-geodata-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.vault.secretStoreName }}
    kind: SecretStore
  target:
    name: cnpg-geodata-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: rheticus_electric_tower/data/geodata
        property: password

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-geonode-core-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.vault.secretStoreName }}
    kind: SecretStore
  target:
    name: geonode-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: rheticus_electric_tower/data/geonode
        property: username
    - secretKey: password
      remoteRef:
        key: rheticus_electric_tower/data/geonode
        property: password
    - secretKey: email
      remoteRef:
        key: rheticus_electric_tower/data/geonode
        property: email