apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.vault.secretStoreName }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.path | quote }}
      version: {{ .Values.vault.version | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.mountPath | quote }}
          role: {{ .Values.vault.vaultRole | quote }}
          serviceAccountRef:
            name: {{ .Values.vault.serviceAccount }}
            namespace: {{ .Release.Namespace }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.vault.serviceAccount }}
  namespace: {{ .Release.Namespace }}